// src/errors/errorCodes.ts

export const ERROR_CODES = {
  // Authentication
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_ACCESS_TOKEN: "INVALID_ACCESS_TOKEN",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_REQUIRED: "REFRESH_TOKEN_REQUIRED",

  // User
  USER_EXISTS: "USER_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ACCOUNT_INACTIVE: "ACCOUNT_INACTIVE",
  ACCOUNT_DELETED: "ACCOUNT_DELETED",

  // Authorization
  FORBIDDEN: "FORBIDDEN",

  // Request
  BAD_REQUEST: "BAD_REQUEST",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",

  // Server
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;